site_name: cmaq_cycle_cloud
nav:
    - Home: 'index.md'
    - User Guide for Cycle Cloud:
        - '1 Description of MVP for Azure CycleCloud': 'user_guide_cyclecloud/system-requirements-cyclecloud.md'
        - 2 Azure CycleCloud Cluster Configure using Azure Web Interface:
             - '2.1 Azure CycleCloud Cluster': 'user_guide_cyclecloud/azure-cyclecloud-cluster.md'
        - 3 CMAQ CONUS Benchark Option 1:
             - '3.1 Install CMAQ on Cycle Cloud': 'user_guide_cyclecloud/software-install-cyclecloud.md'
             - '3.2 Install Input Data': 'user_guide_cyclecloud/input-data-install_cyclecloud.md'
             - '3.3 Run CMAQ CONUS Benchmark on Cycle Cloud': 'user_guide_cyclecloud/run-cmaq-benchmark-cyclecloud.md'
        - 4 CMAQ CONUS Benchmark Option 2:
             - '4.1 Run CMAQ CONUS Benchmark from pre-installed Azure volume': 'user_guide_cyclecloud/preinstall.md'
        - 5 Azure CycleCloud Post-Processing and QA:
             - '5.1 Compile and Run Post-processors': 'user_guide_cyclecloud/post-process-cyclecloud.md'
             - '5.2 Compare timings': 'user_guide_cyclecloud/parse_timing_cyclecloud.md'
             - '5.3 QA CMAQ Output': 'user_guide_cyclecloud/qa_cmaq_run_cyclecloud.md'
             - '5.4 Saving Output': 'user_guide_cyclecloud/copy_output_to_archive_cyclecloud.md'
        - 6 Logout and Delete CycleCloud:
             - '6.1 Logout and Delete Cluster': 'user_guide_cyclecloud/logout_delete_cyclecloud.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'CycleCloud Support': 'help/cyclecloud_support.md'
        - 'CMAQ Support': 'help/cmaq_support.md'
        - 'Azure Free Training': 'help/aws-free-training.md'
        - 'Key References on Cloud Computing': 'help/key-references.md'
    - Future Work:
        - 'Future Work': 'user_guide_cyclecloud/future_work.md'

theme:
  name: readthedocs
