#!/bin/csh

#SBATCH -J test
#SBATCH -t 1:00:00
# #SBATCH -p debug
# #SBATCH -t 4:00:00
#SBATCH -n NPROCS
#SBATCH -o /data/build/liz/run-DOMAIN-CONFIG.logLOGN
#SBATCH -e /data/build/liz/run-DOMAIN-CONFIG.logLOGN

# here are the only two parameters that you need to adjust
setenv npcol NPCOL
setenv nprow NPROW

set domain_name = DOMAIN

setenv o_pnetcdf          .true.
setenv o_reg_netcdf       .true.

set code_path = CODE_PATH

set work_path = $code_path/output

if (! -d $work_path) then
   mkdir $work_path
endif

setenv ncd_64bit_offset T

setenv nlays 35
setenv nvars 146

setenv ncols 459
setenv nrows 299

setenv npcol_row "$npcol $nprow"

# set ext = `printf "%2.2dx%2.2d\n" $npcol $nprow`

# rm -f data*$ext

@ nprocs = $npcol * $nprow

#foreach numtarget (4 6 8)
# foreach stripesize (256 512 1024 2048)
foreach numtarget (1)
  foreach stripesize (1)
    set nt = `printf "%2.2d \n" $numtarget `
    
    cd $work_path

    rm -f data*

    echo " ==d== $npcol $nprow $numtarget $stripesize"

    date
    time mpirun -np $nprocs $code_path/d.x
    date
  end
end
